### ISSUE TITLE
Wink Camera support

### ISSUE THREAD

**Issue by blaineam** [techyowl/WinkWeb#3]
investigate the possibility of supporting wink compatible cameras.

**Comment by 3space123** [comment]
Would this include Ring video doorbell?  Will test for you, if required.

**Comment by blaineam** [comment]
Wink won't allow to obtain image from camera but will allow for arming and disarming the camera and as for the doorbell it doesn't have any recording API points but it does have sensors I may add support for in the future.

**Comment by 3space123** [comment]
Any chance making a "shadeWinks" array?  The switch is a dangerous element in my setup, and I hate to share the switch with the blinds.  Not a huge deal, just curious...

[image1.PNG]
Sent from my iPhone 6S

On Jan 17, 2016, at 11:25 PM, Blaine Miller <notifications@github.com<mailto:notifications@github.com>> wrote:

Wink won't allow to obtain image from camera but will allow for arming and disarming the camera and as for the doorbell it doesn't have any recording API points but it does have sensors I may add support for in the future.

—
Reply to this email directly or view it on GitHubhttps://github.com/techyowl/WinkWeb/issues/3#issuecomment-172421206.

Sent from my iPhone 6S

**Comment by 3space123** [comment]
I apologize, I now think I remember that I set up my Ring video doorbell access via IFTTT, not Wink.

Sent from my iPhone 6S

On Jan 17, 2016, at 11:25 PM, Blaine Miller <notifications@github.com<mailto:notifications@github.com>> wrote:

Wink won't allow to obtain image from camera but will allow for arming and disarming the camera and as for the doorbell it doesn't have any recording API points but it does have sensors I may add support for in the future.

—
Reply to this email directly or view it on GitHubhttps://github.com/techyowl/WinkWeb/issues/3#issuecomment-172421206.

Sent from my iPhone 6S

**Comment by blaineam** [comment]
Interest in supporting this has been dropped
