### ISSUE TITLE
Did you encrypt the username and password for Wink

### ISSUE THREAD

**Issue by AppleTechy** [techyowl/WinkWeb#7]
Did you add the encryption function to the user's username and password login in credentials for Wink? If  not do you have an ETA on when you will have this function complete?

**Comment by blaineam** [comment]
I just implemented encryption for storage but without the end user setting and remembering a secret key it doesn't really do much good from a programmer position seeing as anyone with the code can decrypt the stored passwords still it now stores password using an encryption method.
