### ISSUE TITLE
Calling Wink Rest API- Mac

### ISSUE THREAD

**Issue by AppleTechy** [techyowl/WinkWeb#9]
I have it stuck on this message. I have tried quitting the app and restarting. I have tried logging out and then back in but it still gets stuck. This does appear after the login screen disappears, it then goes to loading devices and then goes the "calling Wink Rest Api" I am using the premade mac application

**Comment by blaineam** [comment]
try the app from the latest commit I was having weird issues as well but I'm not having the issue your having.

**Comment by AppleTechy** [comment]
@techyowl Still having the same issue. Even when I tried to go directly through "https://wink.blainemiller.xyz" It still got stuck on Calling Wink Rest API.

**Comment by blaineam** [comment]
Try sending me the debug email by clicking the menu button at the top left and clicking debug it should take a little bit but then click ok to the first prompt and then send the email message. I'll then be able to better see what your seeing.

**Comment by blaineam** [comment]
Well then I believe that your not properly authenticating with the app. I would try clearing your browsers cookies or deleting the app and reinstalling it and then make sure you enter them correctly. Other possible causes are your behind a firewall that is blocking access to winks API and you'll need to try a different network to confirm this.

**Comment by blaineam** [comment]
closing due to a lack of response and inability to replicate the issue. Feel free to reopen if there is still an issue and if you have detailed steps to replicate the issue with information on OS, Internet, & Networking etc.
